# Generated by Django 4.0.6 on 2022-07-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='graingerMajors',
            new_name='graingerMajor',
        ),
    ]
