# Generated by Django 4.0.6 on 2022-07-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0002_rename_graingermajors_graingermajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AERO_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AGRIBIO_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BIO_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CHEM_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CIVIL_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CS_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ECE_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ENGMECH_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='INDUSTRIAL_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MATS_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MECH_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='NPRE_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PHYS_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_Course_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumbers', models.CharField(max_length=3)),
            ],
        ),
    ]
