# Generated by Django 4.0.5 on 2022-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0006_fileupload_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorName', models.CharField(max_length=100)),
            ],
        ),
    ]
