# Generated by Django 4.0.6 on 2022-07-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0003_aero_course_number_agribio_course_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AERO_Course_Number',
        ),
        migrations.DeleteModel(
            name='AGRIBIO_Course_Number',
        ),
        migrations.DeleteModel(
            name='BIO_Course_Number',
        ),
        migrations.DeleteModel(
            name='CHEM_Course_Number',
        ),
        migrations.DeleteModel(
            name='CIVIL_Course_Number',
        ),
        migrations.DeleteModel(
            name='CS_Course_Number',
        ),
        migrations.DeleteModel(
            name='ECE_Course_Number',
        ),
        migrations.DeleteModel(
            name='ENGMECH_Course_Number',
        ),
        migrations.DeleteModel(
            name='INDUSTRIAL_Course_Number',
        ),
        migrations.DeleteModel(
            name='MATS_Course_Number',
        ),
        migrations.DeleteModel(
            name='MECH_Course_Number',
        ),
        migrations.DeleteModel(
            name='NPRE_Course_Number',
        ),
        migrations.DeleteModel(
            name='PHYS_Course_Number',
        ),
        migrations.DeleteModel(
            name='SYS_Course_Number',
        ),
    ]
