# Generated by Django 4.0.5 on 2022-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontPage', '0005_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='creator',
            field=models.CharField(default='', max_length=100),
        ),
    ]
